---
site_name: Rancho Bud
site_url: https://zaneselvans.github.io/ranchobud
site_description: A package for coordinating collaborative ranked choice budgeting processes.
repo_name: zaneselvans/ranchobud
repo_url: https://github.com/zaneselvans/ranchobud
edit_uri: edit/main/docs/
copyright: '<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY-4.0</a> &copy; 2024 Catalyst Cooperative'

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - search.suggest
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags
  - git-committers:
      repository: zaneselvans/ranchobud
      branch: main
  - git-revision-date-localized

#nav:
#  - Introduction: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zaneselvans
      name: Zane Selvans on GitHub
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/zaneselvans.org
      name: Zane Selvans on BlueSky
    - icon: fontawesome/brands/mastodon
      link: https://social.coop/@ZaneSelvans
      name: Zane Selvans on Mastodon
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zane-selvans
      name: Zane Selvans on LinkedIn
  analytics:
    provider: google
    property: G-EXWBBTVMWK

markdown_extensions:
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - mdx_gh_links
