[project]
site_name = "RanChoVote"
site_description = "A package for coordinating and understanding ranked choice resource allocation contests."
site_author = "Zane Selvans"
site_url = "https://zaneselvans.github.io/ranchovote"
copyright = '<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY-4.0</a> &copy; 2026 Zane Selvans'
repo_name = "zaneselvans/ranchovote"
repo_url = "https://github.com/zaneselvans/ranchovote"
edit_uri = "edit/main/docs"
nav = [
  { Overview = "index.md" },
  { Architecture = "architecture.md" },
  { "RCV Resources" = "rcv-resources.md" },
  { Roadmap = "roadmap.md" },
  { Glossary = "glossary.md" },
  { "Docs Build" = "docs-build.md" },
  { "API Reference" = "api/index.md" },
]

[project.theme]
language = "en"
features = ["content.action.edit", "content.action.view", "search.suggest"]

[project.theme.icon]
repo = "fontawesome/brands/git-alt"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "green"
accent = "yellow"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "green"
accent = "yellow"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to light mode"

[project.extra.analytics]
provider = "google"
property = "G-EXWBBTVMWK"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/zaneselvans"
name = "Zane Selvans on GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/bluesky"
link = "https://bsky.app/profile/zaneselvans.org"
name = "Zane Selvans on BlueSky"

[[project.extra.social]]
icon = "fontawesome/brands/mastodon"
link = "https://social.coop/@ZaneSelvans"
name = "Zane Selvans on Mastodon"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/zane-selvans"
name = "Zane Selvans on LinkedIn"

[project.plugins.search]

[project.plugins.tags]

[project.plugins.gen-files]
scripts = ["scripts/gen_ref_pages.py"]

[project.plugins.mkdocstrings]
default_handler = "python"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
merge_init_into_class = true
separate_signature = true
show_root_full_path = false
show_root_heading = true
show_root_members_full_path = false
show_signature_annotations = true
show_source = false

[project.plugins.git-committers]
repository = "zaneselvans/ranchovote"
branch = "main"

[project.plugins.git-revision-date-localized]

[project.markdown_extensions]
mdx_truly_sane_lists = {}
"pymdownx.highlight" = { anchor_linenums = true, line_spans = "__span", pygments_lang_class = true }
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
"pymdownx.superfences" = {}
toc = { permalink = "#" }
mdx_gh_links = {}
